# Generated by Django 4.0.2 on 2022-03-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='print_length',
            field=models.IntegerField(null=True),
        ),
    ]
